### ISSUE TITLE
New typings broke custom elements for me

### ISSUE THREAD

**Issue by surma** [preactjs/preact#1180]
The new typings introduced in #1116 broke custom elements for me. Is there a workaround, am I using `JSX.IntrinsicElements` wrong or do we need a fix for preact’s typings?

Test case (attach this to `test/ts/VNode-test.s`):

```typescript
class TestCE extends HTMLElement {}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ["test-ce"]: Partial<TestCE>;
    }
  }
}

const MyTestCustomElement = <test-ce><div>hai</div></test-ce>;
```

Error:

```
test/ts/VNode-test.tsx:78:30 - error TS2322: Type '{ children: Element; }' is not assignable to type 'Partial<TestCE>'.
  Types of property 'children' are incompatible.
    Type 'Element' is not assignable to type 'HTMLCollection | undefined'.
      Type 'Element' is not assignable to type 'HTMLCollection'.
        Property 'namedItem' is missing in type 'Element'.

const MyTestCustomElement = <test-ce><div>hai</div></test-ce>;
```
cc @marvinhagemeister

**Comment by marvinhagemeister** [comment]
That's a tough one to crack. Somehow the `children` property is incorrectly inferred in this case. As a workaround you can overwrite the type of `children`:

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      // Overwrite children prop
      ["test-ce"]: Partial<TestCE & { children: any}>;
    }
  }
}
```

**Comment by surma** [comment]
@marvinhagemeister Thanks for the workaround! Yeah, no idea what to do about this one.

**Comment by surma** [comment]
... I just realized that `HTMLElement` defines `children` as `HTMLCollection`.

**Comment by marvinhagemeister** [comment]
@surma ohh good catch, didn't know about that one 👍

**Comment by developit** [comment]
In this case, is `HTMLElement` the same as `JSX.HTMLElement`?

**Comment by Alexendoo** [comment]
I think this is an unfortunate clash of names between what JSX considers as children and the children property of HTML elements

If you wanted to replace the type of children for the definition in `IntrinsicElements` rather than just widen it you could define

```ts
type PreactCustomElement<T, Children = preact.ComponentChildren> = {
	[P in keyof T]?: P extends "children" ? Children : T[P]
}
```

It defaults (ie when using as `PreactCustomElement<TestCE>`) to allowing anything but it can accept only string children for example by doing `PreactCustomElement<TestCE, string>`

This is still less than ideal since it will let you do things like pass addEventListener as a property, I'll think about a better solution for that

**Comment by marvinhagemeister** [comment]
@Alexendoo Awesome, thanks for taking up the torch and getting to the bottom of it. That thought about attributes crossed my mind but somehow I didn't pursue it further. Reading your comment now it makes so much more sense to go that way. Kudos 👍

@surma If you feel like it isn't feel free to ping me to reopen this issue.

**Comment by developit** [comment]
Definitely worth adding a note.  Perhaps a page on the Preact site about usage with TypeScript?  Or a .md here.

**Comment by kuhe** [comment]
@marvinhagemeister 

Did such a note get added? I still can't figure out how to do this as of Preact X rc0. 

https://github.com/kuhe/cannot-extend-instrinsic-elements-demo

**Comment by marvinhagemeister** [comment]
Thanks for pinging me. I'll reopen this ticket and mark it as something for the docs. I'm working on the new ones for X and we should write a section about this in the next week's.

**Comment by pmkroeker** [comment]
For future reference, extending multi-namespaced aspects is weird (see #1467).
For @kuhe:
Easiest to do:
```typescript
// global.d.ts
declare namespace preact.JSX {
  interface IntrinsicElements {
    [tag: string]: any;
  }
}
```

**Comment by kuhe** [comment]
@pmkroeker

I put that into a `global.d.ts` file and it still doesn't compile. I've tried a number of variations of that declaration to get it to merge but have not found a working form.

My setup, now including `global.d.ts`, is in https://github.com/kuhe/cannot-extend-instrinsic-elements-demo.

**Comment by pmkroeker** [comment]
@kuhe You have to make sure to include the file in your `tsconfig.json` file.
```json
{
  "compilerOptions": ...
  "include": [
    "src",
    "global.d.ts"
  ]
}
```
Something like the above.

**Comment by kuhe** [comment]
I tried this include array and it doesn't make a difference. 

I know the `global.d.ts` file was being included even without this `include[]` because the TS compiler errors would change depending on what I had written in it. 

I updated my demo repo to include `include[]` in `tsconfig.json`, and an additional interface in `global.d.ts` that is used in `main.tsx` (push pending github issues resolving today).

**Comment by pmkroeker** [comment]
Strange, it seems as though the behaviour has changed since I last looked into this. Investigating futher!

**Comment by jeremy-coleman** [comment]
Your jsx pragma setting can affect it also. I think using preserve on your root tsconfig and then assigning your desired pragma in your build script is the way to go

**Comment by kuhe** [comment]
@jeremy-coleman 

Using `preserve` leaves out type-checking on JSX, which is something we need to ... preserve.

**Comment by pmkroeker** [comment]
Unfortunately, [declaration merging of namespaces in namespaces is not really supported](https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules) by typescript.

**Comment by kuhe** [comment]
Thanks, Peter.

I will work around it with a slight local modification of Preact X for my team's project(s) so that we can upgrade from 8.x.

**Comment by surma** [comment]
To clarify: Is there currently a workaround for using CEs that does _not_ involve monkey-patching Preact X?

**Comment by jeremy-coleman** [comment]
A definate workaround is to use h instead of jsx

**Comment by developit** [comment]
As per discussion with @surma, this likely circumvents the issue (but is not a solution):

```js
const TestCe = 'test-ce';
const jsx = <TestCe><div>hai</div></TestCe>
```

(JSX turns any tagname with a leading uppercase character or dotted identifier into a variable reference)

**Comment by surma** [comment]
Sadly, TypeScript seems too smart there, too 😅 

```ts
const PinchZoom = "pinch-zoom"

export default class Inspector extends Component {
  render() {
    return (
      <PinchZoom/>
    );
  }
}
```

Errors with

```
src/components/inspector/index.tsx:15:7 - error TS2339: Property 'pinch-zoom' does not exist on type 'JSX.IntrinsicElements'.

15       <PinchZoom />
         ~~~~~~~~~~~~~

src/components/inspector/index.tsx:15:8 - error TS2604: JSX element type 'PinchZoom' does not have any construct or call signatures.

15       <PinchZoom />
          ~~~~~~~~~
```

**Comment by surma** [comment]
Nvm, a simple

```ts
const PinchZoom = "pinch-zoom" as any;
```

solves it :)

**Comment by marvinhagemeister** [comment]
@surma I think I found a solution. Can you verify that this works?

```tsx
import { h } from "preact";
// We just import the raw jsx types again. TS will treat it as a
// new namespace, which can be used to avoid a circular type
// reference due to module augmentation below
import { JSXInternal as JSXI } from "preact/src/jsx";

class TestCE extends HTMLElement {}

declare module "preact" {
	namespace JSXInternal {
		interface IntrinsicElements extends JSXI.IntrinsicElements {
			["test-ce"]: Partial<TestCE>;
		}
	}
}

const MyTestCustomElement = (
	<test-ce>
		<div>hai</div>
	</test-ce>
);
```

**Comment by somarlyonks** [comment]
@marvinhagemeister it works for elements, however

```tsx
import { h } from 'preact'

interface IProps {
  onClick?: h.JSX.MouseEventHandler
  //              ^^^^^^^^^^^^^^^^^ it's broken here since then
}
```

Though solvable by workrounds like `import { JSXInternal } from 'preact'`, I don't think having to do that in most components makes the solution resonable.

**Comment by somarlyonks** [comment]
@marvinhagemeister I think this might be the proper way to do it

```ts
import preact from 'preact'
import { JSXInternal } from 'preact/src/jsx'

declare module 'preact/src/jsx' {
    namespace JSXInternal {
	interface IntrinsicElements {
	    ["test-ce"]: Partial<TestCE>
	}
    }
}
```
It merges namespace `JSXInternal` in this way.

**Comment by talentlessguy** [comment]
I have the same issue

```tsx
import { h, render, Fragment } from 'preact'
import styled from '@emotion/styled'
import { Global, css } from '@emotion/core'

const Header = styled.h1`
  font-size: 5em;
`

const App = () => (
  <Fragment>
    <Global
      styles={css`
        body,
        html {
          margin: 0;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
        }
      `}
    />
    <Header>Hello World</Header>
  </Fragment>
)

render(<App />, document.getElementById('app'))
```

And the warning message is:

```
JSX element type 'Header' does not have any construct or call signatures.
```

**Comment by ForsakenHarmony** [comment]
@talentlessguy that's not an issue with custom elements, `Header` would be a regular component

**Comment by talentlessguy** [comment]
> @talentlessguy that's not an issue with custom elements, `Header` would be a regular component

so it is a problem with Emotion?

**Comment by JoviDeCroock** [comment]
@talentlessguy a custom-element in this case refers to [web-components](https://www.webcomponents.org/) and have nothing to do with a styling abstraction. At first sight I see no problem with the code in itself so I _think_ it's an issue with how the element is perceived after `styled` returns that new `Component`.

It would be good to open a new issue for this specifying the versions of Preact and Emotion and a reproduction if possible.

**Comment by talentlessguy** [comment]
@JoviDeCroock okay, I opened it here #2150

**Comment by talentlessguy** [comment]
> @talentlessguy that's not an issue with custom elements, `Header` would be a regular component

yeah, sorry, gonna remove my comment

**Comment by hbroer** [comment]
Hi, I had a similar problem today. I have a npm package with custom elements which is owned by me, and also a project which depends on that package. My solution was to declare only a interface inside of the web-components package:

`ui-title.ts`
```typescript
export class UiTitle { /* ... */ }

export interface UiTitleAttributes {
    title?: string;
}
```

`index.ts`
```typescript
import {UiTitle, UiTitleAttributes} from "./components/ui-title";

export const defineElements = () => {
    customElements.define("ui-title", UiTitle);
};

export declare interface UiIntrinsicElements<T> {
    "ui-title": UiTitleAttributes & T;
}
```
this compiles to `index.d.ts`:
```typescript
import { UiTitleAttributes } from "./components/ui-title";
export declare const defineElements: () => void;
export declare interface UiIntrinsicElements<T> {
    "ui-title": UiTitleAttributes & T;
}
```

Next I added `src/types/jsx.d.ts` to the dependent project:
```typescript
import {JSXInternal as PreactJSX} from "preact/src/jsx";
import {UiIntrinsicElements} from "@gira/web-components";

declare module "preact" {
    namespace JSXInternal {
        interface IntrinsicElements extends PreactJSX.IntrinsicElements, UiIntrinsicElements<PreactJSX.HTMLAttributes> {}
    }
}
```

Now I can use the `<ui-title/>` element without an error.

**Comment by jakearchibald** [comment]
Thanks @hbroer! Here's what I put in a `d.ts`:

```ts
import { WhateverElementEvent, WhateverElement } from './whatever-el';
import { JSXInternal as PreactJSX } from 'preact/src/jsx';

interface WhateveElAttributes extends PreactJSX.HTMLAttributes {
  someattribute?: string;
  onSomeEvent?: (this: WhateverElement, ev: WhateverElementEvent) => void;
}

declare module 'preact' {
  namespace JSXInternal {
    interface IntrinsicElements extends PreactJSX.IntrinsicElements {
      'whatever-el': WhateveElAttributes;
    }
  }
}
```

**Comment by hbroer** [comment]
It seems that the way we extend the `JSXInternal` namespace it drops the other types and interfaces in that namespace.

As an example the `createContext` function needs this to work again:

```typescript
declare module "preact" {
    namespace JSXInternal {
        /* custom IntrinsicElements extension */
        interface ElementChildrenAttribute extends PreactJSX.ElementChildrenAttribute {}
    }
}
```

Some of the types inside of preacts `index.d.ts` file (181: `createElement` and 199: `h`) are loosing their types too and need the following interfaces to get added

```typescript
declare module "preact" {
    namespace JSXInternal {
        /* custom IntrinsicElements extension */
        interface ElementChildrenAttribute extends PreactJSX.ElementChildrenAttribute {}
        interface HTMLAttributes extends PreactJSX.HTMLAttributes {}
        interface SVGAttributes extends PreactJSX.SVGAttributes {}
    }
}
```
And I wouldn't wonder if there are not more types which will be needed in other coding contexts. 

I don't think it is a good idea to add all types and interfaces to the custom definition only because namespaces can not extended. (`namespace JSXInternal extends PreactJSX {...}` does not work)

I believe we need a better solution to add custom elements to the typing. Any ideas?

**Comment by hbroer** [comment]
Dudes, the answer was right here by @somarlyonks. Overwriting module `preact/src/jsx` instead of `preact` seems to be the key. I overlooked that comment. ^^

```typescript
import {JSXInternal} from "preact/src/jsx";

declare module "preact/src/jsx" {
    namespace JSXInternal {
        /* custom IntrinsicElements extension */
    }
}
```

**Comment by jakearchibald** [comment]
Whoa, nice! You don't even need to import `JSXInternal`. I've updated https://github.com/preactjs/preact/issues/1180#issuecomment-639420544

**Comment by jakearchibald** [comment]
I think this should go on the preact site, but I couldn't get the dev server working due to https://github.com/preactjs/preact-www/issues/605

**Comment by andrewiggins** [comment]
Uh oh - #2575 will break this workaround :( It moves our types from the `src` folder to the `dist` folder so you'd have to change your import to `"preact/dist/jsx"`

**Comment by jakearchibald** [comment]
It would be good to make Typescript + custom elements first class in preact. As in, documented, and only breaks backwards compatibility in major versions.

**Comment by andrewiggins** [comment]
Agreed. I thought we had a test for this in our TypeScript types tests but I seem to be wrong. We should add one to provably demonstrate it works and prevent regressions as well as add documentation like you suggested

**Comment by andrewiggins** [comment]
Hmm seems there was a recent fix in TypeScript that may have resolved some of the issues we were seeing that required `JSXInternal` work arounds. The following fails in 3.9.0-beta but works in 3.9.1-rc

Repo: https://github.com/andrewiggins/cannot-extend-instrinsic-elements-demo/tree/explorations

```typescript
// module.tsx
export interface ModuleCE {
  instanceProp: string;
}

export interface ModuleCEEvent {
  eventProp: string;
}

export interface ModuleCEAttributes extends preact.JSX.HTMLAttributes {
  ceProp?: string;
  onsomeevent?: (this: ModuleCE, ev: ModuleCEEvent) => void;
}

declare module "preact" {
  namespace JSX {
    interface IntrinsicElements {
      "module-custom-element": ModuleCEAttributes;
    }
  }
}
```
```typescript
// app.tsx
import { createElement } from "preact";

export function App() {
  return (
    <div>
      <module-custom-element
        ceProp="ceProp"
        dir="auto" // Inherited prop from HTMLAttributes
        onsomeevent={function (e) {
          console.log(e.eventProp, this.instanceProp);
        }}
      />
    </div>
  );
}
```

There are over 100 fixed issues between 3.9.0-beta and 3.9.1-rc so haven't yet figured out which contributed the fix but thought I'd share what I've found so far.

**Comment by andrewiggins** [comment]
Okay one other update. This pattern seems to work all the back to 3.5.3 (which I think is the min version for Preact's types anyway). Thinking this might be the best guidance for us going forward since I think I remember seeing somewhere the TS team want's to move JSX declarations to be based on the `jsxFactory` (e.g. `React` for react, commonly `h` or `createElement` for `preact`) though that guidance may be a little out of date - haven't been following to closely 😅

```typescript
// Works with TypeScript 3.5.3, 3.6.5, 3.7.5, 3.8.3, 3.9.0-beta, 3.9.5
declare module "preact" {
  namespace createElement.JSX {
    interface IntrinsicElements {
      "module-custom-element": ModuleCEAttributes;
    }
  }
}
```

**Comment by andrewiggins** [comment]
Would love people's thoughts about the patterns I used in `custom-elements.tsx` in #2581!

**Comment by marvinhagemeister** [comment]
Reopening until the TypeScript team has published their fix.

**Comment by Ciantic** [comment]
If you want to embed the type it with your component file, you can use `declare global`, like this:

```typescript
import { h, render } from 'preact';
import type { FunctionComponent } from 'preact';

// This makes it recgonized by the JSX parts in rest of the application:
declare global {
    namespace preact.JSX {
        interface IntrinsicElements {
            'oksidi-sharer': { 'share-url': string };
        }
    }
}

export const OksidiSharer: FunctionComponent<{ shareUrl: string }> = (
    props,
) => {
    return <div>Share this {props.shareUrl}</div>;
};

customElements.define(
    'oksidi-sharer',
    class extends HTMLElement {
        private attachRoot: HTMLElement | ShadowRoot;
        constructor() {
            super();
            this.attachRoot = this.attachShadow({ mode: 'open' });
        }

        connectedCallback() {
            let p = {
                shareUrl: '' + this.attributes.getNamedItem('share-url')?.value,
            };
            render(h(OksidiSharer, p, []), this.attachRoot);
        }

        detachedCallback() {
            render(null, this.attachRoot);
        }
    },
    {},
);
```

**Comment by jakearchibald** [comment]
@andrewiggins that doesn't work for me. It means my preact imports stop working:

```ts
import { h, Component } from 'preact';
```

Module '"preact"' has no exported member 'h'.

**Comment by jakearchibald** [comment]
ffs, it works if the `.d.ts` is a module. Adding `export {}` to the file makes it work. Ugh, I do not understand this part of TypeScript at all.

**Comment by TechQuery** [comment]
```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      ['custom-element']: any;
    }
  }
}
```
which works in React 18, fails in Preact 10: idea2app/React-MobX-Bootstrap-ts#12

**Comment by marvinhagemeister** [comment]
@TechQuery Preact doesn't define the JSX in the global scope like React does. This allows Preact to be used with other JSX-based frameworks at the same time. Pasting the answer from earlier in the thread what the solution looks like:

```ts
declare global {
    namespace preact.createElement.JSX {
        interface IntrinsicElements {
            'custom-element': { 'foo': string; };
        }
    }
}
```

[TypeScript playground](https://www.typescriptlang.org/play?jsx=4#code/PQKhAIAECsGcA8CSBbADgewE4BcDK6BXTAYwFNxVNSBDY7cEYAKAEs0t6BvcAYXXYB2pAdh4ALFgBsAJlQHgAvuABmmfuABElGnQ0BuVuxzhuc6aUwAVdLmyYWAgObhqscGYuKVa5Ju21sAFoPTEDsdEDYOwdHfSYmc2JJaipwR0l0ACNqSRMmcALwAWpkUlhUWnJ-OgA6YipqbFIAUUlSUpEagClcAA08wsHwBybMZUrwRBF7AVgWYlb24Ww3TnyhjYByYgIo-kDSNo7sTYAuE3BN5XR0M-Aomcc9RQMNgoV196YP4nRZ+mo4AAvOAADw7PbIA5HZYqG5AjTZTAacDAAB8QA)

**Comment by TechQuery** [comment]
> @TechQuery Preact doesn't define the JSX in the `global` scope like React does, so trying to extend global JSX types won't work. This allows Preact to be used with other JSX-based frameworks at the same time.
> 
> ```ts
> declare global {
>     namespace preact.JSX {
>         interface IntrinsicElements {
>             'custom-element': { 'foo': string; };
>         }
>     }
> }
> ```
> 
> [TypeScript playground](https://www.typescriptlang.org/play?jsx=4#code/PQKhAIAECsGcA8CSBbADgewE4BcDK6BXTAYwFNxVNSBDY7cEYAKAEs0t6BvcAYXXYB2pAdh4ALFgBsAJlQHgAvuABmmfuABElGnQ0BuVuxzhuc6aUwAVdLmyYWAgObhqscGYuKVa5Ju21sAFoPTEDsdEDYOwdHfSYmc2JJaipwR0l0ACNqSRMmcALwAWpkUlhUWnJ-OgA6AClcAA08wtbwB2wLZUrwRBF7AVgWYgBRSVJSkTdOfLa5gHJiAij+QNJxyex5gC4TcHnldHQd8CiBxz1FAzmChVnbpjvidEH6anAAXnAAHiWV5DWG2E9EO6A+GmymA04GAAD4gA)

For library users, there is no multiple JSX configuration fields in single `tsconfig.json`  file. They usually don't have more configuration files in an application project.

For library developers, they can't define JSX types for all kinds of JSX-compatible engines in the world, so this work must be done by users in their projects manually.

It's not a good developer experience in my opinion.

**Comment by rschristian** [comment]
> For library developers, they can't define JSX types for all kinds of JSX-compatible engines in the world, so this work must be done by users in their projects manually.

There's a pretty small handful of JSX libs that see much use, I don't think asking to add an entry per compatible framework is too much of an ask.

> It's not a good developer experience in my opinion.

It's preferable to the (seemingly only) alternative of competing/fighting types, so I'm not quite sure what you'd like to see change.

---

We've recently added some [docs to our site covering this](https://preactjs.com/guide/v10/typescript#extending-built-in-jsx-types) which should hopefully help out here. I'll close this on out as I don't think there's anything actionable for us here (nor does TS seem interested in changing their somewhat React-centric handling of JSX).
