### ISSUE TITLE
Issues with Suspense/lazy in Preact 10.0.1

### ISSUE THREAD

**Issue by nrdobie** [preactjs/preact#2016]
I am using Parcel + TypeScript + Preact and when i upgraded from Preact version 10.0.0 to 10.0.1 I started to get an error with Suspense.

```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of null
    at t (suspense.js:64)
```

All that changed was the patch version of Preact. I have a repository showing the issue and my settings here: https://github.com/nrdobie/preact-10.0.1-issue. The `master` branch uses `10.0.0` and `broken` branch uses `10.0.1`

 Main Packages Versions: 

- `parcel-bundler@1.12.4`
- `typescript@3.6.4`
- `preact@10.0.1`

**Comment by pmkroeker** [comment]
Ran into the same issue but with Webpack + TS + Preact.

10.0.0 also works fine but updating to 10.0.1 breaks it as above.

**Comment by JoviDeCroock** [comment]
Fix has been PR'ed

**Comment by janbaer** [comment]
I still have this problem with version 10.0.5. I just checked it with version 10.0.0 and it worked with this version. But with all following version the problem still exists.
```
suspense.js:65 Uncaught (in promise) TypeError: t.__u.indexOf is not a function
    at e (suspense.js:65)

```

**Comment by JoviDeCroock** [comment]
Hey,

The target is right in your issue @janbaer so we might need a reproduction for that one since it seems to work in simple cases. This might be a separate issue

**Comment by darklight9811** [comment]
@JoviDeCroock I still struggle with this issue and don't know what is exactly causing this. It complains about a @types/react file

![image](https://user-images.githubusercontent.com/20667774/135957701-dad1ae9a-4e39-40de-9007-28ada0f54041.png)
![image](https://user-images.githubusercontent.com/20667774/135957732-413028ea-a9d8-44ab-8310-ffc7a5a93b1e.png)

**Comment by marvinhagemeister** [comment]
@darklight9811 Please file a new issue for this if you want it to be resolved. Notifications on closed issues are pretty invisible in GitHub's UI, because by default only open issues show up when clicking on the `Issues` tab. Nobody will browse through all closed issues to see if someone made a comment in some closed issue. Please file a new issue.
