### PR TITLE
[ts] Use CSSStyleDeclaration for CSS property list

### LINKED ISSUE #2862: Breaking changes in v10.5.6 - custom css attributes are per type definition not longer allowed
### Reproduction
Any custom style property will now raise an error, example:

```jsx
const element = <div style={{
    '--progress': '0.5'
}}/>
```

will result in
```
error TS2322: Type '{ '--progress': number; }' is not assignable to type 'string | CSSProperties | undefined'.
  Object literal may only specify known properties, and ''--progress'' does not exist in type 'CSSProperties'.

2               style={{'--progress': progress}} 
```

This was introduced in #1797 as `style` is no longer `{ [key: string]: string | number }` and released in [v10.5.6](https://github.com/preactjs/preact/releases/tag/10.5.6).

My environment:
```
OS: Windows 10 Enterprise
Preact: v10.5.7
```

> I hope it's ok that I left out a CodeSandbox example, the problem is clearly visible and broken down to its source.

### Steps to reproduce

See reproduction.

### Expected Behavior

It should be possible to use custom css properties. Yes, it does improve the auto-complete function as we now have types for the `style` property but using custom attributes is now broken or the given object needs to be casted.

### Actual Behavior

It is giving me an error because of:
```ts
interface HTMLAttributes<RefType extends EventTarget = EventTarget>
    extends preact.ClassAttributes<RefType>,
        DOMAttributes<RefType> {
        // Standard HTML Attributes
        ...
        style?: string | CSSProperties; // Breaks custom attributes :(
```

### PR DESCRIPTION
**Pull request by developit**
This removes the validation we added in 10.5.6, since it's unfortunately not yet possible to allow known CSS properties and wildcard `--.*` custom properties (see attempt: https://gist.github.com/developit/3a29186588634648e45e8afb199626df).

Fixes #2862.

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]

**Comment by natemoo-re** [comment]
@developit Wildcard custom properties will be possible when [generalized index signatures](https://github.com/microsoft/TypeScript/pull/26797) lands in [TS 4.2.0](https://github.com/microsoft/TypeScript/issues/41601).

```
type CSSCustomProperties = {
  [key in `--${string}`]?: string | null | undefined;
}
```

Here is a TypeScript [Playground Link](https://www.staging-typescript.org/play?ts=4.2.0-pr-26797-45#code/C4TwDgpgBAwgynGBXAzsA9gWwAoCd2S7ACWEKUAvFAN4BQUUA2gNYQhTEB2UABgLR8AJNTS4uAcwC+PALoB+AFxRREqAB8onJABtt6qEk4ATCADMuEIwG5ak2rVCRYCPAQhFS5KnQaNsHblYQdFNnBFBtCAARCABjbQBDXASSdE55JXhwkEiY+KSU4jS-GSgIAA9gCGNyFU5xKDkoAAosuAjouMTk1M4S-S1dfUMTc05LAEooJXGAN3cbSSgAMjDkNCxXQhIyG1pYtLQoU3R0TJd8bc9GUqpGehoHhgB6Z6hmTnQAd25mhN1vpMnlADtp0LglAByACMkIANA9JAiGD4GFBXlAEpx2LFUBhMFAwJd3KAWv8wV8gWioJCBAAjJKQqEndDw4G0vgspk0rnItEchkAL25kK5iL5qJeb0MH2+vxQAAt0DojGVcPhcBNgSzmac2QwkbQZFYgA) with a working implementation.

**Review by marvinhagemeister — APPROVED** [review]
Sweet 🙌

**Comment by octogonz** [comment]
@developit The `csstype` dependency probably should have been removed in this release:

https://github.com/preactjs/preact/blob/df2dbd83037a8ac2c8555651bcb71971638639f0/package.json#L257

It seems to be not used anywhere in this project.
